import HeaderClient from "components/Navigation/HeaderClient";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "styles/base/index.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <HeaderClient/>
        {children}
        </body>
    </html>
  );
}
